/**
 * Boulevard aesthetics menu (Admin-read inventory 2026-07-22).
 * Source: Website Revamp/runs/2026-07-22/boulevard-config-inventory.json
 * Filtered to active Injectables/Facials/Laser/Microneedling/Peels;
 * excludes add-ons (Add-On/Pronox/Shaving Fee). Prices/durations are
 * Boulevard defaults — not invented. onlineHandoff=true only when a
 * verified rella-booking location/service route exists.
 */

export type BoulevardMenuSeed = {
  serviceSlug: string;
  displayName: string;
  category: "Injectables" | "Facials" | "Laser" | "Microneedling" | "Peels";
  durationMinutes?: number;
  /** Boulevard defaultPrice in cents (list/starting). */
  listPriceCents?: number;
  isConsultation: boolean;
  /** Exact /book/{location}/{slug} handoff exists in rella-booking. */
  onlineHandoff: boolean;
  locations: ReadonlyArray<"napa" | "vacaville">;
  shortDescription?: string;
};

export const BOULEVARD_MENU_SEEDS: readonly BoulevardMenuSeed[] = [
  {
    serviceSlug: "hyperhidrosis-consult",
    displayName: "New Patient Consult",
    category: "Injectables",
    durationMinutes: 15,
    isConsultation: true,
    onlineHandoff: true,
    locations: ["napa"],
    shortDescription: "Complimentary consultation.",
  },
  {
    serviceSlug: "additional-syringe",
    displayName: "Additional Syringe",
    category: "Injectables",
    durationMinutes: 20,
    listPriceCents: 84000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "b-12-injection",
    displayName: "B-12 Injection",
    category: "Injectables",
    durationMinutes: 5,
    listPriceCents: 3500,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "b-complex",
    displayName: "B-Complex",
    category: "Injectables",
    durationMinutes: 5,
    listPriceCents: 6000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "botox-filler",
    displayName: "Botox & Filler",
    category: "Injectables",
    durationMinutes: 65,
    listPriceCents: 70000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "dermal-fillers",
    displayName: "Dermal Fillers",
    category: "Injectables",
    durationMinutes: 5,
    listPriceCents: 84000,
    isConsultation: false,
    onlineHandoff: true,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "easy-gel-prf",
    displayName: "Easy Gel-PRF",
    category: "Injectables",
    durationMinutes: 105,
    listPriceCents: 162000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "tox-established",
    displayName: "Established Patient Tox",
    category: "Injectables",
    durationMinutes: 20,
    listPriceCents: 5000,
    isConsultation: false,
    onlineHandoff: true,
    locations: ["napa"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "glutathione",
    displayName: "Glutathione",
    category: "Injectables",
    durationMinutes: 5,
    listPriceCents: 6000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "hylenex",
    displayName: "Hylenex",
    category: "Injectables",
    durationMinutes: 60,
    listPriceCents: 25000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "injectables-follow-up",
    displayName: "Injectables Follow Up",
    category: "Injectables",
    durationMinutes: 10,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "kybella",
    displayName: "Kybella",
    category: "Injectables",
    durationMinutes: 5,
    listPriceCents: 60000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "botox",
    displayName: "New Patient Tox",
    category: "Injectables",
    durationMinutes: 30,
    listPriceCents: 5000,
    isConsultation: false,
    onlineHandoff: true,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "prf-full-face-1x-treatment",
    displayName: "PRF Full Face 1x treatment",
    category: "Injectables",
    durationMinutes: 80,
    listPriceCents: 132000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "prf-undereye-1x-treatment",
    displayName: "PRF Undereye 1x treatment",
    category: "Injectables",
    durationMinutes: 60,
    listPriceCents: 96000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "prp-hair-restoration",
    displayName: "PRP Hair Restoration",
    category: "Injectables",
    durationMinutes: 65,
    listPriceCents: 84000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "prp-injection",
    displayName: "PRP Injection",
    category: "Injectables",
    durationMinutes: 60,
    listPriceCents: 84000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "sculptra",
    displayName: "Sculptra",
    category: "Injectables",
    durationMinutes: 5,
    listPriceCents: 96000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "vitamin-d",
    displayName: "Vitamin D",
    category: "Injectables",
    durationMinutes: 5,
    listPriceCents: 3500,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "skin-health-consult",
    displayName: "Initial Skin Health Consult",
    category: "Facials",
    durationMinutes: 30,
    isConsultation: true,
    onlineHandoff: true,
    locations: ["napa", "vacaville"],
    shortDescription: "Complimentary consultation.",
  },
  {
    serviceSlug: "acne-facial",
    displayName: "Acne Facial",
    category: "Facials",
    durationMinutes: 75,
    listPriceCents: 16000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "anti-aging-facial",
    displayName: "Anti Aging Facial",
    category: "Facials",
    durationMinutes: 75,
    listPriceCents: 16000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "back-deluxe-hydrafacial-full-back",
    displayName: "Back Deluxe Hydrafacial (Full Back)",
    category: "Facials",
    durationMinutes: 75,
    listPriceCents: 40000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "booty-deluxe-hydrafacial",
    displayName: "Booty Deluxe Hydrafacial",
    category: "Facials",
    durationMinutes: 75,
    listPriceCents: 40000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "hydrafacial-deluxe",
    displayName: "Deluxe Hydrafacial",
    category: "Facials",
    durationMinutes: 45,
    listPriceCents: 30000,
    isConsultation: false,
    onlineHandoff: true,
    locations: ["napa"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "dermaplaning-basic-facial",
    displayName: "Dermaplaning Basic Facial",
    category: "Facials",
    durationMinutes: 45,
    listPriceCents: 8500,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "dermaplaning-deluxe-facial",
    displayName: "Dermaplaning Deluxe Facial",
    category: "Facials",
    durationMinutes: 75,
    listPriceCents: 18500,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "express-facial",
    displayName: "Express Facial",
    category: "Facials",
    durationMinutes: 30,
    listPriceCents: 10000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "hands-hydrafacial",
    displayName: "Hands Hydrafacial",
    category: "Facials",
    durationMinutes: 45,
    listPriceCents: 15000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "jelly-mask",
    displayName: "Jelly Mask",
    category: "Facials",
    durationMinutes: 30,
    listPriceCents: 2500,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "keravive-deluxe-hair-and-scalp-hydrafacial-treatment",
    displayName: "Keravive (Deluxe Hair and Scalp HydraFacial Treatment)",
    category: "Facials",
    durationMinutes: 60,
    listPriceCents: 42000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "microdermabrasion-basic-facial",
    displayName: "Microdermabrasion Basic Facial",
    category: "Facials",
    durationMinutes: 35,
    listPriceCents: 10000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "microdermabrasion-deluxe-facial",
    displayName: "Microdermabrasion Deluxe Facial",
    category: "Facials",
    durationMinutes: 75,
    listPriceCents: 20000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "platinum-hydrafacial",
    displayName: "Platinum Hydrafacial",
    category: "Facials",
    durationMinutes: 75,
    listPriceCents: 39000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "hydrafacial",
    displayName: "Signature Hydrafacial",
    category: "Facials",
    durationMinutes: 45,
    listPriceCents: 24000,
    isConsultation: false,
    onlineHandoff: true,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "laser-consult",
    displayName: "Initial Laser Consult",
    category: "Laser",
    durationMinutes: 30,
    isConsultation: true,
    onlineHandoff: true,
    locations: ["napa", "vacaville"],
    shortDescription: "Complimentary consultation.",
  },
  {
    serviceSlug: "body-tone-muscle-toning-1x-treatment",
    displayName: "Body Tone- Muscle Toning 1x treatment",
    category: "Laser",
    durationMinutes: 45,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "bodysculp-contouring1x-treatment",
    displayName: "BodySculp' Contouring1x treatment",
    category: "Laser",
    durationMinutes: 45,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "c02-coolpeel-full-face",
    displayName: "C02 CoolPeel - Full Face",
    category: "Laser",
    durationMinutes: 45,
    listPriceCents: 144000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "c02-skin-resurfacing",
    displayName: "C02 Skin Resurfacing",
    category: "Laser",
    durationMinutes: 90,
    listPriceCents: 240000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "c02-skin-resurfacing-special-900",
    displayName: "C02 Skin Resurfacing Special $900",
    category: "Laser",
    durationMinutes: 45,
    listPriceCents: 90000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "c02-deka-advance-skin-resurfacing",
    displayName: "C02- Deka Advance Skin Resurfacing",
    category: "Laser",
    durationMinutes: 60,
    listPriceCents: 216000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "c02-follow-up",
    displayName: "C02- Follow up",
    category: "Laser",
    durationMinutes: 45,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "ipl-full-face",
    displayName: "IPL - Full Face",
    category: "Laser",
    durationMinutes: 45,
    listPriceCents: 42000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "ipl-face-neck-decollete-package-3-treatments",
    displayName: "IPL Face + Neck + Decollete Package (3 Treatments)",
    category: "Laser",
    durationMinutes: 85,
    listPriceCents: 156000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "ipl-face-neck-package-3-treatments",
    displayName: "IPL Face + Neck Package (3 Treatments)",
    category: "Laser",
    durationMinutes: 55,
    listPriceCents: 132000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "ipl-full-face-package-3-treatments",
    displayName: "IPL Full Face - Package (3 Treatments)",
    category: "Laser",
    durationMinutes: 45,
    listPriceCents: 108000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "laser-follow-up",
    displayName: "Laser Follow Up",
    category: "Laser",
    durationMinutes: 15,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "laser-hair-removal-large-area-a-la-carte",
    displayName: "Laser Hair Removal Large Area - a la carte",
    category: "Laser",
    durationMinutes: 40,
    listPriceCents: 90000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "laser-hair-removal-medium-area-a-la-carte",
    displayName: "Laser Hair Removal Medium Area - a la carte",
    category: "Laser",
    durationMinutes: 30,
    listPriceCents: 60000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "laser-hair-removal-small-area-a-la-carte",
    displayName: "Laser Hair Removal Small Area - a la carte",
    category: "Laser",
    durationMinutes: 15,
    listPriceCents: 18000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "skin-resurfacing-erbium-face-neck-decollete-package-3-treatments",
    displayName: "Skin Resurfacing Erbium Face + Neck + Decollete Package (3 Treatments)",
    category: "Laser",
    durationMinutes: 5,
    listPriceCents: 242500,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "skin-resurfacing-erbium-face-neck-package-3-treatments",
    displayName: "Skin Resurfacing Erbium Face + Neck Package (3 Treatments)",
    category: "Laser",
    durationMinutes: 5,
    listPriceCents: 222500,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "skin-resurfacing-full-face-erbium",
    displayName: "Skin Resurfacing Full Face - Erbium",
    category: "Laser",
    durationMinutes: 5,
    listPriceCents: 90000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "skin-resurfacing-full-face-erbium-package-3-treatments",
    displayName: "Skin Resurfacing Full Face - Erbium Package (3 Treatments)",
    category: "Laser",
    durationMinutes: 5,
    listPriceCents: 243000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "spider-vein-removal",
    displayName: "Spider Vein Removal",
    category: "Laser",
    durationMinutes: 35,
    listPriceCents: 42000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "spot-treatment-with-lasers",
    displayName: "Spot Treatment with Lasers",
    category: "Laser",
    durationMinutes: 30,
    listPriceCents: 24000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "tattoo-removal",
    displayName: "Tattoo Removal",
    category: "Laser",
    durationMinutes: 40,
    listPriceCents: 25000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "vaginal-rejuvenation",
    displayName: "Vaginal Rejuvenation",
    category: "Laser",
    durationMinutes: 45,
    listPriceCents: 120000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "vaginal-rejuvenation-x3-treatments",
    displayName: "Vaginal Rejuvenation x3 treatments",
    category: "Laser",
    durationMinutes: 45,
    listPriceCents: 120000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "microneedling-consult",
    displayName: "Initial Microneedling Consult",
    category: "Microneedling",
    durationMinutes: 30,
    isConsultation: true,
    onlineHandoff: true,
    locations: ["vacaville"],
    shortDescription: "Complimentary consultation.",
  },
  {
    serviceSlug: "rf-microneedling",
    displayName: "RF Microneedling",
    category: "Microneedling",
    durationMinutes: 5,
    listPriceCents: 90000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "rf-microneedling-face-neck-decollete-package-3-treatments",
    displayName: "RF Microneedling Face + Neck + Decollete Package (3 Treatments)",
    category: "Microneedling",
    durationMinutes: 5,
    listPriceCents: 315000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "rf-microneedling-face-neck-package-3-treatments",
    displayName: "RF Microneedling Face + Neck Package (3 Treatments)",
    category: "Microneedling",
    durationMinutes: 5,
    listPriceCents: 279000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "rf-microneedling-face-package-3-treatments",
    displayName: "RF Microneedling Face Package (3 Treatments)",
    category: "Microneedling",
    durationMinutes: 5,
    listPriceCents: 243000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "skin-stylus-microneedling",
    displayName: "Skin Stylus Microneedling",
    category: "Microneedling",
    durationMinutes: 5,
    listPriceCents: 60000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "skin-stylus-microneedling-package-3-treatments",
    displayName: "Skin Stylus Microneedling Package (3 Treatments)",
    category: "Microneedling",
    durationMinutes: 5,
    listPriceCents: 150000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "biorepeel",
    displayName: "BioRePeel",
    category: "Peels",
    durationMinutes: 70,
    listPriceCents: 34000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "biorepeel-package-4-treatments",
    displayName: "BioRePeel Package (4 Treatments)",
    category: "Peels",
    durationMinutes: 70,
    listPriceCents: 122500,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "micropeel-plus-20",
    displayName: "MicroPeel Plus 20",
    category: "Peels",
    durationMinutes: 60,
    listPriceCents: 18000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "micropeel-sensitive",
    displayName: "MicroPeel Sensitive",
    category: "Peels",
    durationMinutes: 60,
    listPriceCents: 16000,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "tca-peel",
    displayName: "TCA Peel",
    category: "Peels",
    durationMinutes: 70,
    listPriceCents: 38500,
    isConsultation: false,
    onlineHandoff: false,
    locations: ["napa", "vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
  {
    serviceSlug: "universal-peel",
    displayName: "Universal Peel",
    category: "Peels",
    durationMinutes: 45,
    isConsultation: false,
    onlineHandoff: true,
    locations: ["vacaville"],
    shortDescription: "Bookable Boulevard service — details confirmed during booking.",
  },
] as const;
